### ISSUE TITLE
Two tools shown as active in same time

### ISSUE THREAD

**Issue by Symbian9** [sk1project/sk1-wx#148] opened 2018-11-09 17:12 UTC
### Details

sK1 version: `2.0rc4_20181109`
OS: *Debian 9.x* (x86_64)

### Steps to reproduce

1. Run sK1;
2. Create new document;
3. Set "Create curve" tool  as active and draw some pice of curve;
4. Change tool to another one (for example, "Create rectangle");

### Current behaviors

After switching from "Create curve" to some other tool, "Create curve" tool still shown as active alongside with active tool.

![pic.1](http://i.imgur.com/CHmBVyv.png)

So, in same time two tools shown as active on toolbar in same time.

### Expected behaviors

Only current (one) tool should be active on toolbar.

### Log console output

```
 INFO     | 06:59:38 PM | sk1.application --> Logging started
 INFO     | 06:59:38 PM | sk1.application --> Config is updated
 INFO     | 06:59:39 PM | sk1.application --> Application is initialized
 INFO     | 06:59:39 PM | sk1.application --> To start, create new document or open existing
 INFO     | 06:59:50 PM | sk1.application --> <SK2> document model is updated successfully
 INFO     | 06:59:50 PM | sk1.application --> Document is changed
 INFO     | 06:59:50 PM | sk1.application --> New document created
 INFO     | 06:59:53 PM | sk1.application --> No selection
 INFO     | 06:59:55 PM | sk1.application --> No selection
 ERROR    | 06:59:56 PM | sk1.document.canvas --> Painting error list index out of range
Traceback (most recent call last):
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/canvas.py", line 465, in paint
    self.controller.repaint()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 133, in repaint
    self.timer_callback()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 431, in repaint_draw
    self.curve_point_doc)
  File "/usr/lib/sk1-wx-2.0rc4/uc2/libgeom/points.py", line 49, in contra_point
    return [2.0 * p1[0] - p0[0], 2.0 * p1[1] - p0[1]]
IndexError: list index out of range
 ERROR    | 06:59:58 PM | sk1.document.canvas --> Painting error list index out of range
Traceback (most recent call last):
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/canvas.py", line 465, in paint
    self.controller.repaint()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 133, in repaint
    self.timer_callback()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 431, in repaint_draw
    self.curve_point_doc)
  File "/usr/lib/sk1-wx-2.0rc4/uc2/libgeom/points.py", line 49, in contra_point
    return [2.0 * p1[0] - p0[0], 2.0 * p1[1] - p0[1]]
IndexError: list index out of range
 ERROR    | 06:59:58 PM | sk1.document.canvas --> Painting error list index out of range
Traceback (most recent call last):
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/canvas.py", line 465, in paint
    self.controller.repaint()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 133, in repaint
    self.timer_callback()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 431, in repaint_draw
    self.curve_point_doc)
  File "/usr/lib/sk1-wx-2.0rc4/uc2/libgeom/points.py", line 49, in contra_point
    return [2.0 * p1[0] - p0[0], 2.0 * p1[1] - p0[1]]
IndexError: list index out of range
 INFO     | 06:59:58 PM | sk1.application --> Curve object in selection (Layer 1)
 INFO     | 06:59:58 PM | sk1.application --> Curve object in selection (Layer 1)
 INFO     | 06:59:59 PM | sk1.application --> Curve object in selection (Layer 1)
 CRITICAL | 07:00:00 PM | sk1.app_stdout --> Traceback (most recent call last):
  File "/usr/lib/sk1-wx-2.0rc4/sk1/parts/tools.py", line 84, in _mouse_up
    self.onchange()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/pwidgets/actions.py", line 129, in __call__
    self.callback(*self.callable_args)
  File "/usr/lib/sk1-wx-2.0rc4/sk1/app_proxy.py", line 243, in set_mode
    self.app.current_doc.canvas.set_mode(mode)
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/canvas.py", line 148, in set_mode
    self.controller.start_()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 62, in start_
    self.update_from_selection()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 197, in update_from_selection
    self.update_from_obj(sel_objs[0])
TypeError: update_from_obj() takes exactly 1 argument (2 given)
 ERROR    | 07:00:02 PM | sk1.document.canvas --> Painting error list index out of range
Traceback (most recent call last):
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/canvas.py", line 465, in paint
    self.controller.repaint()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 133, in repaint
    self.timer_callback()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 431, in repaint_draw
    self.curve_point_doc)
  File "/usr/lib/sk1-wx-2.0rc4/uc2/libgeom/points.py", line 49, in contra_point
    return [2.0 * p1[0] - p0[0], 2.0 * p1[1] - p0[1]]
IndexError: list index out of range
 ERROR    | 07:00:02 PM | sk1.document.canvas --> Painting error list index out of range
Traceback (most recent call last):
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/canvas.py", line 465, in paint
    self.controller.repaint()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 133, in repaint
    self.timer_callback()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 431, in repaint_draw
    self.curve_point_doc)
  File "/usr/lib/sk1-wx-2.0rc4/uc2/libgeom/points.py", line 49, in contra_point
    return [2.0 * p1[0] - p0[0], 2.0 * p1[1] - p0[1]]
IndexError: list index out of range
 ERROR    | 07:00:03 PM | sk1.document.canvas --> Painting error list index out of range
Traceback (most recent call last):
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/canvas.py", line 465, in paint
    self.controller.repaint()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 133, in repaint
    self.timer_callback()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 431, in repaint_draw
    self.curve_point_doc)
  File "/usr/lib/sk1-wx-2.0rc4/uc2/libgeom/points.py", line 49, in contra_point
    return [2.0 * p1[0] - p0[0], 2.0 * p1[1] - p0[1]]
IndexError: list index out of range
 ERROR    | 07:00:03 PM | sk1.document.canvas --> Painting error list index out of range
Traceback (most recent call last):
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/canvas.py", line 465, in paint
    self.controller.repaint()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 133, in repaint
    self.timer_callback()
  File "/usr/lib/sk1-wx-2.0rc4/sk1/document/controllers/paint_ctrl.py", line 431, in repaint_draw
    self.curve_point_doc)
  File "/usr/lib/sk1-wx-2.0rc4/uc2/libgeom/points.py", line 49, in contra_point
    return [2.0 * p1[0] - p0[0], 2.0 * p1[1] - p0[1]]
IndexError: list index out of range
 INFO     | 07:00:05 PM | sk1.application --> Curve object in selection (Layer 1)
 INFO     | 07:00:05 PM | sk1.application --> Curve object in selection (Layer 1)
```

**Comment by maxim-s-barabash** [comment] 2018-12-24 19:41
```diff
--- src/sk1/document/controllers/paint_ctrl.py	(date 1544769922000)
+++ src/sk1/document/controllers/paint_ctrl.py	(date 1545680357000)
@@ -326,8 +326,8 @@
             self.clear_data()
         p = event.get_point()
         self.curve_point, self.curve_point_doc = self.snap.snap_point(p)[1:]
-        self.control_point2 = []
-        self.control_point2_doc = []
+        self.control_point2 = self.curve_point
+        self.control_point2_doc = self.curve_point_doc
         self.create = True
         self.init_timer()
 ```

**Comment by maxim-s-barabash** [comment] 2018-12-26 21:59
the error is not fixed.
Сode preceding this error.
src/sk1/document/controllers/paint_ctrl.py
```python
435                self.control_point1_doc = contra_point(self.control_point2_doc,
436                                                       self.curve_point_doc)
```
insofar as self.control_point2_doc == []

**Comment by maxim-s-barabash** [comment] 2018-12-26 23:50
- Set "Create curve" tool
- click mouse down and fast mouse move

**Comment by sk1project** [comment] 2018-12-27 00:06
@maxim-s-barabash Cannot reproduce it. But found the problem in:
- Set "Create curve" tool
- press mouse left button down and quickly clicking mouse right button.
```
 ERROR    | 01:54:44 AM | sk1.document.canvas --> Painting error list index out of range
Traceback (most recent call last):
  File "/home/igor/Projects/sk1-wx/src/sk1/document/canvas.py", line 466, in paint
    self.controller.repaint()
  File "/home/igor/Projects/sk1-wx/src/sk1/document/controllers/paint_ctrl.py", line 136, in repaint
    self.timer_callback()
  File "/home/igor/Projects/sk1-wx/src/sk1/document/controllers/paint_ctrl.py", line 438, in repaint_draw
    self.curve_point_doc)
  File "/home/igor/Projects/sk1-wx/src/uc2/libgeom/points.py", line 49, in contra_point
    return [2.0 * p1[0] - p0[0], 2.0 * p1[1] - p0[1]]
IndexError: list index out of range
```
This issue doesn't freeze tool buttons like in ticket subj, but produces error stack trace in app log. Actually this is another bug. And this should be fixed in repaint_draw() method, not by initializing control point because the point is absent. Such initializing may be problem source for other issues

**Comment by sk1project** [comment] 2018-12-27 00:39
BTW right click issue has been fixed for all creator tools. Please check master.

**Comment by maxim-s-barabash** [comment] 2018-12-27 07:12
Do the same thing just use the left mouse button.

**Comment by sk1project** [comment] 2018-12-31 15:47
subj fixed

**Closed by sk1project** 2018-12-31 15:47 UTC
Labels: bug
